new mqtt topics format

diff --git a/scripts/Makefile b/scripts/Makefile
--- a/scripts/Makefile
+++ b/scripts/Makefile
@@ -2,99 +2,103 @@ CONNECT_HOST ?= localhost
 CONNECT_PORT ?= 8083
 CONNECT_URL  := http://$(CONNECT_HOST):$(CONNECT_PORT)
 
-CONFIG ?= ./configs/mqtt-sensors-source.json
-CONNECTOR := $(basename $(CONFIG:.json=))
+CONFIG ?= ./configs/mqtt-sensors-raw-source.json
+CONNECTOR := $(basename $(notdir $(CONFIG:.json=)))
 
 FLINK_JOBMANAGER ?= flink-jobmanager
-FLINK_BIN        := docker exec -i $(FLINK_JOBMANAGER) /opt/flink/bin
-FLINK_SQL_ENRICHER_PATH   ?= /opt/flink/sql/mqtt_enriched_temporal_join.sql
-FLINK_SQL_RESENT_SUMMARY_PATH   ?= /opt/flink/sql/mqtt_resent_summary.sql
-JOB_ID           ?=
+FLINK_BIN := docker exec -i $(FLINK_JOBMANAGER) /opt/flink/bin
+
+FLINK_SQL_MEASUREMENT_PATH ?= /opt/flink/sql/mqtt_measurement.sql
+FLINK_SQL_ENRICHED_PATH ?= /opt/flink/sql/mqtt_enriched.sql
+FLINK_SQL_RESENT_SUMMARY_PATH ?= /opt/flink/sql/mqtt_resent_summary.sql
+
 KAFKA_BIN := docker compose exec -i kafka /usr/bin
 
-kafka-topics-init:
-	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists \
-	  --bootstrap-server kafka:9092 \
-	  --topic mqtt_humidity \
-	  --partitions 1 --replication-factor 1 || true
-	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists \
-	  --bootstrap-server kafka:9092 \
-	  --topic mqtt_location \
-	  --partitions 1 --replication-factor 1 || true
-	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists \
-	  --bootstrap-server kafka:9092 \
-	  --topic mqtt_state \
-	  --partitions 1 --replication-factor 1 || true
-	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists \
-	  --bootstrap-server kafka:9092 \
-	  --topic mqtt_enriched \
-	  --partitions 1 --replication-factor 1 || true
-	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists \
-	  --bootstrap-server kafka:9092 \
-	  --topic mqtt_recent_summary \
-	  --partitions 1 --replication-factor 1 || true
-	@echo "Kafka topics ready."
+.PHONY: kafka-topics-init \
+        connector-up connector-down connect-connectors \
+        mqtt-sensors-raw-source-up mqtt-sensors-raw-source-down \
+        sensor-enriched-postgres-sink-up sensor-enriched-postgres-sink-down \
+        sensor-enriched-redis-sink-up sensor-enriched-redis-sink-down \
+        mqtt-analytics-redis-sink-up mqtt-analytics-redis-sink-down \
+        flink-measurement-up flink-enriched-up flink-summary-up \
+        flink-jobs-up flink-jobs-down flink-job-list \
+        stack-up stack-down emulator-up emulator-down \
+        connectors-up connectors-down \
+        platform-start platform-stop
 
-.PHONY: connector-up connector-down connect-connectors \
-        mqtt-sensors-source-up mqtt-sensors-source-down \
-        mqtt-postgres-sink-up mqtt-postgres-sink-down \
-        mqtt-enriched-redis-sink-up mqtt-enriched-redis-sink-down \
-        flink-job-up flink-job-down flink-job-list \
-        mqtt-recent-summary-redis-sink-up mqtt-recent-summary-redis-sink-down
+kafka-topics-init:
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic mqtt_humidity_raw --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic mqtt_temperature_raw --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic mqtt_location_raw --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic mqtt_state_raw --partitions 1 --replication-factor 1 || true
+
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic sensor.humidity.v1 --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic sensor.temperature.v1 --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic sensor.location.v1 --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic sensor.state.v1 --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic sensor.parse.errors --partitions 1 --replication-factor 1 || true
+
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic sensor.measurement.v1 --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic sensor.enriched.v1 --partitions 1 --replication-factor 1 || true
+
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic mqtt_recent_summary --partitions 1 --replication-factor 1 || true
+	@$(KAFKA_BIN)/kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic mqtt_low_humidity_streak --partitions 1 --replication-factor 1 || true
+
+	@echo "Kafka topics ready."
 
 connector-up:
 	@curl -sS -X POST "$(CONNECT_URL)/connectors" \
 	  -H "Content-Type: application/json" \
 	  --data @$(CONFIG) \
-	  -o /dev/null \
-	  && echo "Done." \
-	  || echo "Request failed"
+	  && echo "" || echo "Request failed"
 
 connector-down:
 	@curl -sS -X DELETE "$(CONNECT_URL)/connectors/$(CONNECTOR)" \
-	  -o /dev/null \
-	  && echo "Done." \
-	  || echo "Request failed"
-
-mqtt-sensors-source-up:
-	$(MAKE) connector-up CONFIG=./configs/mqtt-sensors-source.json
-
-mqtt-sensors-source-down:
-	$(MAKE) connector-down CONFIG=./configs/mqtt-sensors-source.json
-
-mqtt-postgres-sink-up:
-	$(MAKE) connector-up CONFIG=./configs/mqtt-postgres-sink.json
-
-mqtt-postgres-sink-down:
-	$(MAKE) connector-down CONFIG=./configs/mqtt-postgres-sink.json
-
-mqtt-enriched-redis-sink-up:
-	$(MAKE) connector-up CONFIG=./configs/mqtt-enriched-redis-sink.json
-
-mqtt-enriched-redis-sink-down:
-	$(MAKE) connector-down CONFIG=./configs/mqtt-enriched-redis-sink.json
-
-mqtt-recent-summary-redis-sink-up:
-	$(MAKE) connector-up CONFIG=./configs/mqtt-recent-summary-redis-sink.json
-
-mqtt-recent-summary-redis-sink-down:
-	$(MAKE) connector-down CONFIG=./configs/mqtt-recent-summary-redis-sink.json
+	  && echo "" || echo "Request failed"
 
 connect-connectors:
-	@curl -sS "$(CONNECT_URL)/connectors" \
-	  -o /dev/null \
-	  && echo "Done." \
-	  || echo "Request failed"
+	@curl -sS "$(CONNECT_URL)/connectors" && echo "" || echo "Request failed"
+
+mqtt-sensors-raw-source-up:
+	$(MAKE) connector-up CONFIG=./configs/mqtt-sensors-raw-source.json
+
+mqtt-sensors-raw-source-down:
+	$(MAKE) connector-down CONFIG=./configs/mqtt-sensors-raw-source.json
+
+sensor-enriched-postgres-sink-up:
+	$(MAKE) connector-up CONFIG=./configs/sensor-enriched-postgres-sink.json
+
+sensor-enriched-postgres-sink-down:
+	$(MAKE) connector-down CONFIG=./configs/sensor-enriched-postgres-sink.json
+
+sensor-enriched-redis-sink-up:
+	$(MAKE) connector-up CONFIG=./configs/sensor-enriched-redis-sink.json
+
+sensor-enriched-redis-sink-down:
+	$(MAKE) connector-down CONFIG=./configs/sensor-enriched-redis-sink.json
+
+mqtt-analytics-redis-sink-up:
+	$(MAKE) connector-up CONFIG=./configs/mqtt-analytics-redis-sink.json
+
+mqtt-analytics-redis-sink-down:
+	$(MAKE) connector-down CONFIG=./configs/mqtt-analytics-redis-sink.json
+
+flink-measurement-up:
+	@echo "Starting measurement job..."
+	@$(FLINK_BIN)/sql-client.sh -f $(FLINK_SQL_MEASUREMENT_PATH)
+
+flink-enriched-up:
+	@echo "Starting enriched job..."
+	@$(FLINK_BIN)/sql-client.sh -f $(FLINK_SQL_ENRICHED_PATH)
+
+flink-summary-up:
+	@echo "Starting summary job..."
+	@$(FLINK_BIN)/sql-client.sh -f $(FLINK_SQL_RESENT_SUMMARY_PATH)
 
 flink-jobs-up: kafka-topics-init
-	@$(FLINK_BIN)/sql-client.sh -f $(FLINK_SQL_ENRICHER_PATH) \
-	  >/dev/null 2>&1 \
-	  && echo "Enricher job started." \
-	  || echo "Enricher job failed"
-	@$(FLINK_BIN)/sql-client.sh -f $(FLINK_SQL_RESENT_SUMMARY_PATH) \
-	  >/dev/null 2>&1 \
-	  && echo "Summary job started." \
-	  || echo "Summary job failed"
+	@$(MAKE) flink-measurement-up
+	@$(MAKE) flink-enriched-up
+	@$(MAKE) flink-summary-up
 
 flink-jobs-down:
 	@jobs=`$(FLINK_BIN)/flink list | awk '/RUNNING/ {print $$4}'`; \
@@ -103,16 +107,13 @@ flink-jobs-down:
 	else \
 	  for job in $$jobs; do \
 	    echo "Cancelling Flink job $$job..."; \
-	    $(FLINK_BIN)/flink cancel $$job >/dev/null 2>&1 || echo "Failed to cancel $$job"; \
+	    $(FLINK_BIN)/flink cancel $$job || echo "Failed to cancel $$job"; \
 	  done; \
 	  echo "Done."; \
 	fi
 
 flink-job-list:
-	@$(FLINK_BIN)/flink list
-
-.PHONY: stack-up stack-down emulator-up emulator-down \
-        platform-start platform-stop connectors-up connectors-down
+	@$(FLINK_BIN)/flink list -a
 
 stack-up:
 	@docker compose up -d --build
@@ -127,29 +128,29 @@ emulator-up:
 	@echo "MQTT emulator started."
 
 emulator-down:
-	@docker compose down mqtt-emulator || true
+	@docker compose rm -sf mqtt-emulator >/dev/null 2>&1 || true
 	@echo "MQTT emulator stopped."
 
 connectors-up:
-	@$(MAKE) mqtt-sensors-source-up
-	@$(MAKE) mqtt-postgres-sink-up
-	@$(MAKE) mqtt-enriched-redis-sink-up
-	@$(MAKE) mqtt-recent-summary-redis-sink-up
+	@$(MAKE) mqtt-sensors-raw-source-up
+	@$(MAKE) sensor-enriched-postgres-sink-up
+	@$(MAKE) sensor-enriched-redis-sink-up
+	@$(MAKE) mqtt-analytics-redis-sink-up
 	@echo "All connectors up."
 
 connectors-down:
-	@$(MAKE) mqtt-recent-summary-redis-sink-down || true
-	@$(MAKE) mqtt-enriched-redis-sink-down || true
-	@$(MAKE) mqtt-postgres-sink-down || true
-	@$(MAKE) mqtt-sensors-source-down || true
+	@$(MAKE) mqtt-analytics-redis-sink-down || true
+	@$(MAKE) sensor-enriched-redis-sink-down || true
+	@$(MAKE) sensor-enriched-postgres-sink-down || true
+	@$(MAKE) mqtt-sensors-raw-source-down || true
 	@echo "All connectors down."
 
 platform-start: stack-up
 	@$(MAKE) emulator-down
-	@$(MAKE) flink-jobs-up
 	@$(MAKE) connectors-up
+	@$(MAKE) flink-jobs-up
 	@$(MAKE) emulator-up
-	@echo "Platform started (jobs+connectors ready, emulator started last)."
+	@echo "Platform started."
 
 platform-stop:
 	@$(MAKE) emulator-down
@@ -157,4 +158,3 @@ platform-stop:
 	@$(MAKE) flink-jobs-down || true
 	@$(MAKE) stack-down
 	@echo "Platform stopped."
-
